# Generated by Django 2.1.4 on 2018-12-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0002_auto_20181216_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('track_number', models.SmallIntegerField()),
                ('disc_number', models.SmallIntegerField()),
                ('duration_ms', models.IntegerField()),
                ('spotify_id', models.CharField(max_length=64)),
                ('preview_url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums')),
                ('artists', models.ManyToManyField(to='artists.Artists')),
            ],
        ),
    ]
