# Generated by Django 2.1.4 on 2018-12-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='preview_url',
        ),
    ]
