# Generated by Django 2.1.4 on 2018-12-16 13:28

import albums.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0002_auto_20181216_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album_type', models.CharField(choices=[(albums.models.AlbumTypes('album'), 'album'), (albums.models.AlbumTypes('single'), 'single'), (albums.models.AlbumTypes('compilation'), 'compilation')], max_length=15)),
                ('genres', models.CharField(max_length=4096)),
                ('spotify_id', models.CharField(max_length=64)),
                ('img_url', models.URLField()),
                ('release_date', models.DateField()),
                ('artists', models.ManyToManyField(to='artists.Artists')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='albums',
            name='users',
            field=models.ManyToManyField(related_name='album_updates', through='albums.Updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
