# Generated by Django 2.1.4 on 2018-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
